### ISSUE TITLE
Extract base classes and utilities out to an asgi-auth package

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-auth-github#3]
I probably won't do this until I've written at least one other authentication plugin, on the basis that you shouldn't refactor until you've written the code at least twice (ideally thrice).

**Comment by simonw** [comment]
I actually undid this base class concept entirely in 7e8b678908bca418b6c0561ae02bc527b4b93a69 - I'm closing this as `wontfix`. I may well do this in the future but it doesn't need to be tracked in this repository.

**Comment by ananis25** [comment]
Use-case: Provide Google login as an alternative since non-developers tend not to have a Github account. As indicated in #45 , this package is very easy to use as a standalone OAuth provider.

Patching `github_auth.py` to do this wasn't very difficult, despite Google's poor documentation of OAuth using simple http. Admittedly, I'm not very familiar with the OAuth security model so naively extending this package to alternative providers might not be safe.

Does it make sense to reopen this issue? I'll try to submit a PR if it helps deciding. Thanks!

**Comment by ananis25** [comment]
Hi @simonw , I modified my local patch to add Google as an auth provider and submitted as PR #52 . It still needs some work but is usable. 
Do you think it'd be a useful addition to this repository? Happy to refine the PR. Thank you.
